### ISSUE TITLE
Design rules for the most relevant repositories 

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pr-custom-review#32]
Check if [processbot's approval criteria](https://github.com/paritytech/parity-processbot#criteria-for-merge) + [requirements](https://github.com/paritytech/ci_cd/issues/233) can be translated to the `rules` according to the implementation of #31.

In doing so, provide examples of how exactly those configurations will be.

- [x] #34
- [x] #36 
- [x] #35 

# Common requirements

## Locks

- [x] Done (waiting for #43)

From https://github.com/paritytech/ci_cd/issues/233#issue-1026394650

> Any PR which removes or changes
> - A line containing the emoji lock, or
> - A line which immediately follows a line containing only a comment which contains the emoji lock

must have approvals from at least one team lead **as well as** either the CTO or the CEO.

## processbot

- [x] Done (waiting for #41)

From [merge criteria](https://github.com/paritytech/parity-processbot#criteria-for-merge)

> A Pull Request needs either (meaning, only one of the following requirements needs to be fulfilled)
> - core-dev member approvals (2 for Substrate, 1 otherwise), or
> - one substrateteamleads member approval

```yaml
rules:
  - name: Developers
    check_type: diff
    condition: .*
    any:
      - min_approvals: 2
        teams:
          - core-devs
      - min_approvals: 1
        teams:
          - substrateteamleads
```

**Comment by joao-paulo-parity** [comment]
with #31 it'll be possible to implement the [processbot criteria](https://github.com/paritytech/parity-processbot#criteria-for-merge)

> A Pull Request needs either (meaning, only one of the following requirements needs to be fulfilled)

> - core-dev member approvals (2 for Substrate, 1 otherwise), or
> - one substrateteamleads member approval

```yml
rules:
  - name: Foo
    check_type: diff
    condition: .*
    any:
      - min_approvals: 1
        teams:
          - core-devs
      - min_approvals: 2
        teams:
          - substrateteamleads
```

this unblocks part of #34, #35, #36
