### ISSUE TITLE
Support Polkadot's requirements

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pr-custom-review#34]
# Polkadot

## Requirements

From https://github.com/paritytech/ci_cd/issues/233#issue-1026394650

> Any PR that touches the runtime/lib.rs must have an approval from at least two team leads

```yaml
rules:
  - name: Runtime
    condition: runtime/.*/lib\.rs$
    check_type: changed_files
    min_approvals: 2
    teams:
      - substrateteamleads
```
