### ISSUE TITLE
Support "OR" conditions

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pr-custom-review#37]
As demonstrated by the use-cases of https://github.com/paritytech/pr-custom-review/issues/32, we need a way to express "OR" conditions. e.g. 

A Pull Request needs either (meaning, only one of the following requirements needs to be fulfilled)

- core-dev member approvals (2 for Substrate, 1 otherwise), or
- one substrateteamleads member approval

**Comment by TriplEight** [comment]
This would be a valuable addition, but let's not include it into the MVP.

**Comment by joao-paulo-parity** [comment]
This "OR" feature is necessary for deprecating the approval criteria of processbot, otherwise you'll deploy this action _in addition to_ the approval rules of processbot. I was hoping we'd be able to get rid of that logic in favor of this check. I suspect two simultaneous review systems in the same repository will be confusing.

For what it's worth I don't think it would be complicated to implement this.

**Comment by TriplEight** [comment]
(three review systems, don't forget about that of CODEOWNERS xD)

**Comment by TriplEight** [comment]
Yea, you're right. Moreover, this might introduce breaking changes in the reviewers configs.

**Comment by joao-paulo-parity** [comment]
An "AND" condition would also be useful for modeling one of the requirements (_granted this requirement will be implemented as a built-in check, therefore we don't have to care about doing it through the configuration API_)

> must have approvals from at least one team lead **as well as** either the CTO or the CEO

Instead of the current

```yml
rules:
  - name: Team leads locks review
    condition: 🔒[^\n]*\n[+|-]|(^|\n)[+|-][^\n]*🔒
    check_type: diff
    min_approvals: 1
    teams:
      - substrateteamleads
  - name: CTO/CEO locks review
    condition: 🔒[^\n]*\n[+|-]|(^|\n)[+|-][^\n]*🔒
    check_type: diff
    min_approvals: 1
    teams:
      - locks-review-team
```

We could have

```yml
rules:
  - name: Locks review
    condition: 🔒[^\n]*\n[+|-]|(^|\n)[+|-][^\n]*🔒
    check_type: diff
    all: # any: for "OR"
      - min_approvals: 1
        teams:
          - substrateteamleads
      - min_approvals: 1
        teams:
          - locks-review-team
```

Given that "AND" is not strictly necessary for us right now, perhaps leave it as a future improvement.
