### ISSUE TITLE
Allow for optionally specifying target branches for rules

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pr-custom-review#55]
Problem: users might be inconvenienced by the CI status not passing when they want to merge a branch into another branch **which is not `master`**, e.g. a big feature branch (that does happen from time to time).

Solution: allow for specifying `target_branches` which means the rule will only be active if those branches are the targets of the pull request.

```diff
rules:
  - name: Foo
+   target_branches: 
+     - master
+     - release-v[0-9]
    condition: .*
    check_type: diff
    min_approvals: 1
```

**Comment by joao-paulo-parity** [comment]
This can be implemented with workflows' `if` directly

```yaml
steps:
  - uses: paritytech/pr-custom-review@v1
    if: ${{ github.base_ref == 'master' }}
```
