### ISSUE TITLE
Implement "AND Distinct" rule

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pr-custom-review#70]
Problem: given the requirements being discussed in https://github.com/paritytech/pr-custom-review/pull/67/files#r830921395, the following requirement

> Basically, the corner case here would be not to accept reviews as sufficient when there are two reviews from @paritytech/polkadotleads and none from @paritytech/locks-review

can't be expressed by the current "AND" or "OR" rules.

Solution: implement the "AND Distinct" rule where approvals from one rule don't count towards other rules.

```yml
rules:
  - name: Rule name
    condition: .*
    check_type: diff
    # this rule requires distinct approvals for each criterion. effectively it will
    # only be fulfilled if both user1 and user2 approve since user1's approval on
    # the first criterion will not count towards the second.
    and_distinct:
      - min_approvals: 1
        users:
          - user1
      - min_approvals: 1
        users:
          - user1
          - user2
```
